/*
* generated by Xtext
*/
package de.uni_paderborn.fujaba.muml.allocation.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AllocationSpecificationStandaloneSetup extends AllocationSpecificationStandaloneSetupGenerated{

	public static void doSetup() {
		new AllocationSpecificationStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

