language: java
sudo: false
jdk:
  - oraclejdk8

deploy:
  provider: script
  script: 
  wget https://svn-serv.cs.upb.de/mechatronicuml/trunk/DevelopmentTools/maven_pre_build.sh
  sh maven_pre_build.sh
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  mvn clean verify
 
  
  
notifications:
  email:
    recipients:
    - upohl@upb.de
    on_success: change
    on_failure: always
