/**
 * generated by Xtext 2.11.0
 */
package de.fraunhofer.iem.ide;

import com.google.inject.Injector;
import de.fraunhofer.iem.SeminarStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SeminarIdeSetup extends SeminarStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from SeminarIdeModule to Module");
  }
}
