/*
* generated by Xtext
*/
package de.uni_paderborn.fujaba.muml.allocation.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.uni_paderborn.fujaba.muml.allocation.language.services.AllocationSpecificationGrammarAccess;

public class AllocationSpecificationParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AllocationSpecificationGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.uni_paderborn.fujaba.muml.allocation.language.parser.antlr.internal.InternalAllocationSpecificationParser createParser(XtextTokenStream stream) {
		return new de.uni_paderborn.fujaba.muml.allocation.language.parser.antlr.internal.InternalAllocationSpecificationParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Specification";
	}
	
	public AllocationSpecificationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AllocationSpecificationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
