/*
* generated by Xtext
*/
package de.uni_paderborn.fujaba.muml.allocation.language.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.ocl.examples.xtext.essentialocl.services.EssentialOCLGrammarAccess;

@Singleton
public class AllocationSpecificationLanguageGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class SpecificationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Specification");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSpecificationCSAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cServicesAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final RuleCall cServicesServiceParserRuleCall_3_0_0 = (RuleCall)cServicesAssignment_3_0.eContents().get(0);
		private final Assignment cConstraintsAssignment_3_1 = (Assignment)cAlternatives_3.eContents().get(1);
		private final RuleCall cConstraintsConstraintParserRuleCall_3_1_0 = (RuleCall)cConstraintsAssignment_3_1.eContents().get(0);
		private final Assignment cMeasureAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMeasureMeasureFunctionParserRuleCall_4_0 = (RuleCall)cMeasureAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		////import "platform:/resource/de.uni_paderborn.fujaba.muml.allocation.language/model/LanguageSpecificationCS.ecore#/cs" as cs
		//Specification returns cs::SpecificationCS:
		//	{cs::SpecificationCS} name=ID "{" (services+=Service | constraints+=Constraint)* measure=MeasureFunction? "}";
		public ParserRule getRule() { return rule; }

		//{cs::SpecificationCS} name=ID "{" (services+=Service | constraints+=Constraint)* measure=MeasureFunction? "}"
		public Group getGroup() { return cGroup; }

		//{cs::SpecificationCS}
		public Action getSpecificationCSAction_0() { return cSpecificationCSAction_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDParserRuleCall_1_0() { return cNameIDParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//(services+=Service | constraints+=Constraint)*
		public Alternatives getAlternatives_3() { return cAlternatives_3; }

		//services+=Service
		public Assignment getServicesAssignment_3_0() { return cServicesAssignment_3_0; }

		//Service
		public RuleCall getServicesServiceParserRuleCall_3_0_0() { return cServicesServiceParserRuleCall_3_0_0; }

		//constraints+=Constraint
		public Assignment getConstraintsAssignment_3_1() { return cConstraintsAssignment_3_1; }

		//Constraint
		public RuleCall getConstraintsConstraintParserRuleCall_3_1_0() { return cConstraintsConstraintParserRuleCall_3_1_0; }

		//measure=MeasureFunction?
		public Assignment getMeasureAssignment_4() { return cMeasureAssignment_4; }

		//MeasureFunction
		public RuleCall getMeasureMeasureFunctionParserRuleCall_4_0() { return cMeasureMeasureFunctionParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class ServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Service");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cServiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDimensionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDimensionsQosDimensionParserRuleCall_3_0 = (RuleCall)cDimensionsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Service returns cs::ServiceCS:
		//	"service" name=ID "{" dimensions+=QosDimension* "}";
		public ParserRule getRule() { return rule; }

		//"service" name=ID "{" dimensions+=QosDimension* "}"
		public Group getGroup() { return cGroup; }

		//"service"
		public Keyword getServiceKeyword_0() { return cServiceKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDParserRuleCall_1_0() { return cNameIDParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//dimensions+=QosDimension*
		public Assignment getDimensionsAssignment_3() { return cDimensionsAssignment_3; }

		//QosDimension
		public RuleCall getDimensionsQosDimensionParserRuleCall_3_0() { return cDimensionsQosDimensionParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class QosDimensionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QosDimension");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cQosKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueValueTupleDescriptorParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cDescriptorsKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTupleDescriptorsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_7_0 = (RuleCall)cTupleDescriptorsAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cTupleDescriptorsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_8_1_0 = (RuleCall)cTupleDescriptorsAssignment_8_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cOclKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cMetricAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cMetricModelParserRuleCall_11_0 = (RuleCall)cMetricAssignment_11.eContents().get(0);
		private final Keyword cSemicolonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//QosDimension returns cs::QoSDimensionCS:
		//	"qos" name=ID "{" "value" value=ValueTupleDescriptor ";" "descriptors"
		//	tupleDescriptors+=ComponentResourceTupleDescriptor ("," tupleDescriptors+=ComponentResourceTupleDescriptor)* ";" "ocl"
		//	metric=Model ";" "}";
		public ParserRule getRule() { return rule; }

		//"qos" name=ID "{" "value" value=ValueTupleDescriptor ";" "descriptors"
		//tupleDescriptors+=ComponentResourceTupleDescriptor ("," tupleDescriptors+=ComponentResourceTupleDescriptor)* ";" "ocl"
		//metric=Model ";" "}"
		public Group getGroup() { return cGroup; }

		//"qos"
		public Keyword getQosKeyword_0() { return cQosKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDParserRuleCall_1_0() { return cNameIDParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"value"
		public Keyword getValueKeyword_3() { return cValueKeyword_3; }

		//value=ValueTupleDescriptor
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//ValueTupleDescriptor
		public RuleCall getValueValueTupleDescriptorParserRuleCall_4_0() { return cValueValueTupleDescriptorParserRuleCall_4_0; }

		//";"
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }

		//"descriptors"
		public Keyword getDescriptorsKeyword_6() { return cDescriptorsKeyword_6; }

		//tupleDescriptors+=ComponentResourceTupleDescriptor
		public Assignment getTupleDescriptorsAssignment_7() { return cTupleDescriptorsAssignment_7; }

		//ComponentResourceTupleDescriptor
		public RuleCall getTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_7_0() { return cTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_7_0; }

		//("," tupleDescriptors+=ComponentResourceTupleDescriptor)*
		public Group getGroup_8() { return cGroup_8; }

		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }

		//tupleDescriptors+=ComponentResourceTupleDescriptor
		public Assignment getTupleDescriptorsAssignment_8_1() { return cTupleDescriptorsAssignment_8_1; }

		//ComponentResourceTupleDescriptor
		public RuleCall getTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_8_1_0() { return cTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_8_1_0; }

		//";"
		public Keyword getSemicolonKeyword_9() { return cSemicolonKeyword_9; }

		//"ocl"
		public Keyword getOclKeyword_10() { return cOclKeyword_10; }

		//metric=Model
		public Assignment getMetricAssignment_11() { return cMetricAssignment_11; }

		//Model
		public RuleCall getMetricModelParserRuleCall_11_0() { return cMetricModelParserRuleCall_11_0; }

		//";"
		public Keyword getSemicolonKeyword_12() { return cSemicolonKeyword_12; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class ConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Constraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConstraintKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cLocationConstraintParserRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final RuleCall cResourceConstraintParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		private final RuleCall cRequiredHardwareResourceInstanceConstraintParserRuleCall_1_2 = (RuleCall)cAlternatives_1.eContents().get(2);
		
		//Constraint returns cs::ConstraintCS:
		//	"constraint" (LocationConstraint | ResourceConstraint | RequiredHardwareResourceInstanceConstraint);
		public ParserRule getRule() { return rule; }

		//"constraint" (LocationConstraint | ResourceConstraint | RequiredHardwareResourceInstanceConstraint)
		public Group getGroup() { return cGroup; }

		//"constraint"
		public Keyword getConstraintKeyword_0() { return cConstraintKeyword_0; }

		//LocationConstraint | ResourceConstraint | RequiredHardwareResourceInstanceConstraint
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//LocationConstraint
		public RuleCall getLocationConstraintParserRuleCall_1_0() { return cLocationConstraintParserRuleCall_1_0; }

		//ResourceConstraint
		public RuleCall getResourceConstraintParserRuleCall_1_1() { return cResourceConstraintParserRuleCall_1_1; }

		//RequiredHardwareResourceInstanceConstraint
		public RuleCall getRequiredHardwareResourceInstanceConstraintParserRuleCall_1_2() { return cRequiredHardwareResourceInstanceConstraintParserRuleCall_1_2; }
	}

	public class LocationConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LocationConstraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeLocationConstraintTypeEnumRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDescriptorsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTupleDescriptorsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTupleDescriptorsLocationTupleDescriptorParserRuleCall_4_0 = (RuleCall)cTupleDescriptorsAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTupleDescriptorsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTupleDescriptorsLocationTupleDescriptorParserRuleCall_5_1_0 = (RuleCall)cTupleDescriptorsAssignment_5_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cOclKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cExpressionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cExpressionModelParserRuleCall_8_0 = (RuleCall)cExpressionAssignment_8.eContents().get(0);
		private final Keyword cSemicolonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//LocationConstraint returns cs::LocationConstraintCS:
		//	type=LocationConstraintType name=ID? "{" "descriptors" tupleDescriptors+=LocationTupleDescriptor (","
		//	tupleDescriptors+=LocationTupleDescriptor)* ";" "ocl" expression=Model ";" "}";
		public ParserRule getRule() { return rule; }

		//type=LocationConstraintType name=ID? "{" "descriptors" tupleDescriptors+=LocationTupleDescriptor (","
		//tupleDescriptors+=LocationTupleDescriptor)* ";" "ocl" expression=Model ";" "}"
		public Group getGroup() { return cGroup; }

		//type=LocationConstraintType
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//LocationConstraintType
		public RuleCall getTypeLocationConstraintTypeEnumRuleCall_0_0() { return cTypeLocationConstraintTypeEnumRuleCall_0_0; }

		//name=ID?
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDParserRuleCall_1_0() { return cNameIDParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"descriptors"
		public Keyword getDescriptorsKeyword_3() { return cDescriptorsKeyword_3; }

		//tupleDescriptors+=LocationTupleDescriptor
		public Assignment getTupleDescriptorsAssignment_4() { return cTupleDescriptorsAssignment_4; }

		//LocationTupleDescriptor
		public RuleCall getTupleDescriptorsLocationTupleDescriptorParserRuleCall_4_0() { return cTupleDescriptorsLocationTupleDescriptorParserRuleCall_4_0; }

		//("," tupleDescriptors+=LocationTupleDescriptor)*
		public Group getGroup_5() { return cGroup_5; }

		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//tupleDescriptors+=LocationTupleDescriptor
		public Assignment getTupleDescriptorsAssignment_5_1() { return cTupleDescriptorsAssignment_5_1; }

		//LocationTupleDescriptor
		public RuleCall getTupleDescriptorsLocationTupleDescriptorParserRuleCall_5_1_0() { return cTupleDescriptorsLocationTupleDescriptorParserRuleCall_5_1_0; }

		//";"
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }

		//"ocl"
		public Keyword getOclKeyword_7() { return cOclKeyword_7; }

		//expression=Model
		public Assignment getExpressionAssignment_8() { return cExpressionAssignment_8; }

		//Model
		public RuleCall getExpressionModelParserRuleCall_8_0() { return cExpressionModelParserRuleCall_8_0; }

		//";"
		public Keyword getSemicolonKeyword_9() { return cSemicolonKeyword_9; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class ResourceConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ResourceConstraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResourceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLhsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cLhsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLhsValueTupleDescriptorParserRuleCall_4_0 = (RuleCall)cLhsAssignment_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cRhsKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cRhsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cRhsValueTupleDescriptorParserRuleCall_7_0 = (RuleCall)cRhsAssignment_7.eContents().get(0);
		private final Keyword cSemicolonKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cDescriptorsKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cTupleDescriptorsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_10_0 = (RuleCall)cTupleDescriptorsAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cCommaKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cTupleDescriptorsAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_11_1_0 = (RuleCall)cTupleDescriptorsAssignment_11_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cOclKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cExpressionAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cExpressionModelParserRuleCall_14_0 = (RuleCall)cExpressionAssignment_14.eContents().get(0);
		private final Keyword cSemicolonKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		
		//ResourceConstraint returns cs::ResourceConstraintCS:
		//	"resource" name=ID? "{" "lhs" lhs=ValueTupleDescriptor ";" "rhs" rhs=ValueTupleDescriptor ";" "descriptors"
		//	tupleDescriptors+=ComponentResourceTupleDescriptor ("," tupleDescriptors+=ComponentResourceTupleDescriptor)* ";" "ocl"
		//	expression=Model ";" "}";
		public ParserRule getRule() { return rule; }

		//"resource" name=ID? "{" "lhs" lhs=ValueTupleDescriptor ";" "rhs" rhs=ValueTupleDescriptor ";" "descriptors"
		//tupleDescriptors+=ComponentResourceTupleDescriptor ("," tupleDescriptors+=ComponentResourceTupleDescriptor)* ";" "ocl"
		//expression=Model ";" "}"
		public Group getGroup() { return cGroup; }

		//"resource"
		public Keyword getResourceKeyword_0() { return cResourceKeyword_0; }

		//name=ID?
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDParserRuleCall_1_0() { return cNameIDParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"lhs"
		public Keyword getLhsKeyword_3() { return cLhsKeyword_3; }

		//lhs=ValueTupleDescriptor
		public Assignment getLhsAssignment_4() { return cLhsAssignment_4; }

		//ValueTupleDescriptor
		public RuleCall getLhsValueTupleDescriptorParserRuleCall_4_0() { return cLhsValueTupleDescriptorParserRuleCall_4_0; }

		//";"
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }

		//"rhs"
		public Keyword getRhsKeyword_6() { return cRhsKeyword_6; }

		//rhs=ValueTupleDescriptor
		public Assignment getRhsAssignment_7() { return cRhsAssignment_7; }

		//ValueTupleDescriptor
		public RuleCall getRhsValueTupleDescriptorParserRuleCall_7_0() { return cRhsValueTupleDescriptorParserRuleCall_7_0; }

		//";"
		public Keyword getSemicolonKeyword_8() { return cSemicolonKeyword_8; }

		//"descriptors"
		public Keyword getDescriptorsKeyword_9() { return cDescriptorsKeyword_9; }

		//tupleDescriptors+=ComponentResourceTupleDescriptor
		public Assignment getTupleDescriptorsAssignment_10() { return cTupleDescriptorsAssignment_10; }

		//ComponentResourceTupleDescriptor
		public RuleCall getTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_10_0() { return cTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_10_0; }

		//("," tupleDescriptors+=ComponentResourceTupleDescriptor)*
		public Group getGroup_11() { return cGroup_11; }

		//","
		public Keyword getCommaKeyword_11_0() { return cCommaKeyword_11_0; }

		//tupleDescriptors+=ComponentResourceTupleDescriptor
		public Assignment getTupleDescriptorsAssignment_11_1() { return cTupleDescriptorsAssignment_11_1; }

		//ComponentResourceTupleDescriptor
		public RuleCall getTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_11_1_0() { return cTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_11_1_0; }

		//";"
		public Keyword getSemicolonKeyword_12() { return cSemicolonKeyword_12; }

		//"ocl"
		public Keyword getOclKeyword_13() { return cOclKeyword_13; }

		//expression=Model
		public Assignment getExpressionAssignment_14() { return cExpressionAssignment_14; }

		//Model
		public RuleCall getExpressionModelParserRuleCall_14_0() { return cExpressionModelParserRuleCall_14_0; }

		//";"
		public Keyword getSemicolonKeyword_15() { return cSemicolonKeyword_15; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
	}

	public class RequiredHardwareResourceInstanceConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RequiredHardwareResourceInstanceConstraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRequiredHardwareResourceInstanceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDescriptorsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTupleDescriptorsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_4_0 = (RuleCall)cTupleDescriptorsAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTupleDescriptorsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_5_1_0 = (RuleCall)cTupleDescriptorsAssignment_5_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cOclKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cExpressionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cExpressionModelParserRuleCall_8_0 = (RuleCall)cExpressionAssignment_8.eContents().get(0);
		private final Keyword cSemicolonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//RequiredHardwareResourceInstanceConstraint returns cs::RequiredHardwareResourceInstanceConstraintCS:
		//	"requiredHardwareResourceInstance" name=ID? "{" "descriptors" tupleDescriptors+=ComponentResourceTupleDescriptor (","
		//	tupleDescriptors+=ComponentResourceTupleDescriptor)* ";" "ocl" expression=Model ";" "}";
		public ParserRule getRule() { return rule; }

		//"requiredHardwareResourceInstance" name=ID? "{" "descriptors" tupleDescriptors+=ComponentResourceTupleDescriptor (","
		//tupleDescriptors+=ComponentResourceTupleDescriptor)* ";" "ocl" expression=Model ";" "}"
		public Group getGroup() { return cGroup; }

		//"requiredHardwareResourceInstance"
		public Keyword getRequiredHardwareResourceInstanceKeyword_0() { return cRequiredHardwareResourceInstanceKeyword_0; }

		//name=ID?
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDParserRuleCall_1_0() { return cNameIDParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"descriptors"
		public Keyword getDescriptorsKeyword_3() { return cDescriptorsKeyword_3; }

		//tupleDescriptors+=ComponentResourceTupleDescriptor
		public Assignment getTupleDescriptorsAssignment_4() { return cTupleDescriptorsAssignment_4; }

		//ComponentResourceTupleDescriptor
		public RuleCall getTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_4_0() { return cTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_4_0; }

		//("," tupleDescriptors+=ComponentResourceTupleDescriptor)*
		public Group getGroup_5() { return cGroup_5; }

		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//tupleDescriptors+=ComponentResourceTupleDescriptor
		public Assignment getTupleDescriptorsAssignment_5_1() { return cTupleDescriptorsAssignment_5_1; }

		//ComponentResourceTupleDescriptor
		public RuleCall getTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_5_1_0() { return cTupleDescriptorsComponentResourceTupleDescriptorParserRuleCall_5_1_0; }

		//";"
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }

		//"ocl"
		public Keyword getOclKeyword_7() { return cOclKeyword_7; }

		//expression=Model
		public Assignment getExpressionAssignment_8() { return cExpressionAssignment_8; }

		//Model
		public RuleCall getExpressionModelParserRuleCall_8_0() { return cExpressionModelParserRuleCall_8_0; }

		//";"
		public Keyword getSemicolonKeyword_9() { return cSemicolonKeyword_9; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class LocationTupleDescriptorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LocationTupleDescriptor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cInstanceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInstanceIDParserRuleCall_1_0 = (RuleCall)cInstanceAssignment_1.eContents().get(0);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSecondInstanceAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSecondInstanceIDParserRuleCall_3_0 = (RuleCall)cSecondInstanceAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//LocationTupleDescriptor returns cs::LocationTupleDescriptorCS:
		//	"(" instance=ID "," secondInstance=ID ")";
		public ParserRule getRule() { return rule; }

		//"(" instance=ID "," secondInstance=ID ")"
		public Group getGroup() { return cGroup; }

		//"("
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }

		//instance=ID
		public Assignment getInstanceAssignment_1() { return cInstanceAssignment_1; }

		//ID
		public RuleCall getInstanceIDParserRuleCall_1_0() { return cInstanceIDParserRuleCall_1_0; }

		//","
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }

		//secondInstance=ID
		public Assignment getSecondInstanceAssignment_3() { return cSecondInstanceAssignment_3; }

		//ID
		public RuleCall getSecondInstanceIDParserRuleCall_3_0() { return cSecondInstanceIDParserRuleCall_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class ValueTupleDescriptorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ValueTupleDescriptor");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueIDParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//ValueTupleDescriptor returns cs::ValueTupleDescriptorCS:
		//	value=ID;
		public ParserRule getRule() { return rule; }

		//value=ID
		public Assignment getValueAssignment() { return cValueAssignment; }

		//ID
		public RuleCall getValueIDParserRuleCall_0() { return cValueIDParserRuleCall_0; }
	}

	public class ComponentResourceTupleDescriptorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ComponentResourceTupleDescriptor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cInstanceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInstanceIDParserRuleCall_1_0 = (RuleCall)cInstanceAssignment_1.eContents().get(0);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cHwresinstanceAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cHwresinstanceIDParserRuleCall_3_0 = (RuleCall)cHwresinstanceAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ComponentResourceTupleDescriptor returns cs::ComponentResourceTupleDescriptorCS:
		//	"(" instance=ID "," hwresinstance=ID ")";
		public ParserRule getRule() { return rule; }

		//"(" instance=ID "," hwresinstance=ID ")"
		public Group getGroup() { return cGroup; }

		//"("
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }

		//instance=ID
		public Assignment getInstanceAssignment_1() { return cInstanceAssignment_1; }

		//ID
		public RuleCall getInstanceIDParserRuleCall_1_0() { return cInstanceIDParserRuleCall_1_0; }

		//","
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }

		//hwresinstance=ID
		public Assignment getHwresinstanceAssignment_3() { return cHwresinstanceAssignment_3; }

		//ID
		public RuleCall getHwresinstanceIDParserRuleCall_3_0() { return cHwresinstanceIDParserRuleCall_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class MeasureFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MeasureFunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMeasureKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cServicesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cServicesServiceCSCrossReference_1_0 = (CrossReference)cServicesAssignment_1.eContents().get(0);
		private final RuleCall cServicesServiceCSIDParserRuleCall_1_0_1 = (RuleCall)cServicesServiceCSCrossReference_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cPlusSignKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cServicesAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cServicesServiceCSCrossReference_2_1_0 = (CrossReference)cServicesAssignment_2_1.eContents().get(0);
		private final RuleCall cServicesServiceCSIDParserRuleCall_2_1_0_1 = (RuleCall)cServicesServiceCSCrossReference_2_1_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//MeasureFunction returns cs::MeasureFunctionCS:
		//	"measure" services+=[cs::ServiceCS] ("+" services+=[cs::ServiceCS])* ";";
		public ParserRule getRule() { return rule; }

		//"measure" services+=[cs::ServiceCS] ("+" services+=[cs::ServiceCS])* ";"
		public Group getGroup() { return cGroup; }

		//"measure"
		public Keyword getMeasureKeyword_0() { return cMeasureKeyword_0; }

		//services+=[cs::ServiceCS]
		public Assignment getServicesAssignment_1() { return cServicesAssignment_1; }

		//[cs::ServiceCS]
		public CrossReference getServicesServiceCSCrossReference_1_0() { return cServicesServiceCSCrossReference_1_0; }

		//ID
		public RuleCall getServicesServiceCSIDParserRuleCall_1_0_1() { return cServicesServiceCSIDParserRuleCall_1_0_1; }

		//("+" services+=[cs::ServiceCS])*
		public Group getGroup_2() { return cGroup_2; }

		//"+"
		public Keyword getPlusSignKeyword_2_0() { return cPlusSignKeyword_2_0; }

		//services+=[cs::ServiceCS]
		public Assignment getServicesAssignment_2_1() { return cServicesAssignment_2_1; }

		//[cs::ServiceCS]
		public CrossReference getServicesServiceCSCrossReference_2_1_0() { return cServicesServiceCSCrossReference_2_1_0; }

		//ID
		public RuleCall getServicesServiceCSIDParserRuleCall_2_1_0_1() { return cServicesServiceCSIDParserRuleCall_2_1_0_1; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	
	
	public class LocationConstraintTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "LocationConstraintType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSAME_LOCATIONEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSAME_LOCATIONSameLocationKeyword_0_0 = (Keyword)cSAME_LOCATIONEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDIFFERENT_LOCATIONEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDIFFERENT_LOCATIONDifferentLocationKeyword_1_0 = (Keyword)cDIFFERENT_LOCATIONEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum LocationConstraintType returns cs::LocationConstraintTypes:
		//	SAME_LOCATION="sameLocation" | DIFFERENT_LOCATION="differentLocation";
		public EnumRule getRule() { return rule; }

		//SAME_LOCATION="sameLocation" | DIFFERENT_LOCATION="differentLocation"
		public Alternatives getAlternatives() { return cAlternatives; }

		//SAME_LOCATION="sameLocation"
		public EnumLiteralDeclaration getSAME_LOCATIONEnumLiteralDeclaration_0() { return cSAME_LOCATIONEnumLiteralDeclaration_0; }

		//"sameLocation"
		public Keyword getSAME_LOCATIONSameLocationKeyword_0_0() { return cSAME_LOCATIONSameLocationKeyword_0_0; }

		//DIFFERENT_LOCATION="differentLocation"
		public EnumLiteralDeclaration getDIFFERENT_LOCATIONEnumLiteralDeclaration_1() { return cDIFFERENT_LOCATIONEnumLiteralDeclaration_1; }

		//"differentLocation"
		public Keyword getDIFFERENT_LOCATIONDifferentLocationKeyword_1_0() { return cDIFFERENT_LOCATIONDifferentLocationKeyword_1_0; }
	}
	
	private SpecificationElements pSpecification;
	private ServiceElements pService;
	private QosDimensionElements pQosDimension;
	private ConstraintElements pConstraint;
	private LocationConstraintElements pLocationConstraint;
	private ResourceConstraintElements pResourceConstraint;
	private RequiredHardwareResourceInstanceConstraintElements pRequiredHardwareResourceInstanceConstraint;
	private LocationConstraintTypeElements unknownRuleLocationConstraintType;
	private LocationTupleDescriptorElements pLocationTupleDescriptor;
	private ValueTupleDescriptorElements pValueTupleDescriptor;
	private ComponentResourceTupleDescriptorElements pComponentResourceTupleDescriptor;
	private MeasureFunctionElements pMeasureFunction;
	
	private final Grammar grammar;

	private EssentialOCLGrammarAccess gaEssentialOCL;

	@Inject
	public AllocationSpecificationLanguageGrammarAccess(GrammarProvider grammarProvider,
		EssentialOCLGrammarAccess gaEssentialOCL) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaEssentialOCL = gaEssentialOCL;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.uni_paderborn.fujaba.muml.allocation.language.AllocationSpecificationLanguage".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public EssentialOCLGrammarAccess getEssentialOCLGrammarAccess() {
		return gaEssentialOCL;
	}

	
	////import "platform:/resource/de.uni_paderborn.fujaba.muml.allocation.language/model/LanguageSpecificationCS.ecore#/cs" as cs
	//Specification returns cs::SpecificationCS:
	//	{cs::SpecificationCS} name=ID "{" (services+=Service | constraints+=Constraint)* measure=MeasureFunction? "}";
	public SpecificationElements getSpecificationAccess() {
		return (pSpecification != null) ? pSpecification : (pSpecification = new SpecificationElements());
	}
	
	public ParserRule getSpecificationRule() {
		return getSpecificationAccess().getRule();
	}

	//Service returns cs::ServiceCS:
	//	"service" name=ID "{" dimensions+=QosDimension* "}";
	public ServiceElements getServiceAccess() {
		return (pService != null) ? pService : (pService = new ServiceElements());
	}
	
	public ParserRule getServiceRule() {
		return getServiceAccess().getRule();
	}

	//QosDimension returns cs::QoSDimensionCS:
	//	"qos" name=ID "{" "value" value=ValueTupleDescriptor ";" "descriptors"
	//	tupleDescriptors+=ComponentResourceTupleDescriptor ("," tupleDescriptors+=ComponentResourceTupleDescriptor)* ";" "ocl"
	//	metric=Model ";" "}";
	public QosDimensionElements getQosDimensionAccess() {
		return (pQosDimension != null) ? pQosDimension : (pQosDimension = new QosDimensionElements());
	}
	
	public ParserRule getQosDimensionRule() {
		return getQosDimensionAccess().getRule();
	}

	//Constraint returns cs::ConstraintCS:
	//	"constraint" (LocationConstraint | ResourceConstraint | RequiredHardwareResourceInstanceConstraint);
	public ConstraintElements getConstraintAccess() {
		return (pConstraint != null) ? pConstraint : (pConstraint = new ConstraintElements());
	}
	
	public ParserRule getConstraintRule() {
		return getConstraintAccess().getRule();
	}

	//LocationConstraint returns cs::LocationConstraintCS:
	//	type=LocationConstraintType name=ID? "{" "descriptors" tupleDescriptors+=LocationTupleDescriptor (","
	//	tupleDescriptors+=LocationTupleDescriptor)* ";" "ocl" expression=Model ";" "}";
	public LocationConstraintElements getLocationConstraintAccess() {
		return (pLocationConstraint != null) ? pLocationConstraint : (pLocationConstraint = new LocationConstraintElements());
	}
	
	public ParserRule getLocationConstraintRule() {
		return getLocationConstraintAccess().getRule();
	}

	//ResourceConstraint returns cs::ResourceConstraintCS:
	//	"resource" name=ID? "{" "lhs" lhs=ValueTupleDescriptor ";" "rhs" rhs=ValueTupleDescriptor ";" "descriptors"
	//	tupleDescriptors+=ComponentResourceTupleDescriptor ("," tupleDescriptors+=ComponentResourceTupleDescriptor)* ";" "ocl"
	//	expression=Model ";" "}";
	public ResourceConstraintElements getResourceConstraintAccess() {
		return (pResourceConstraint != null) ? pResourceConstraint : (pResourceConstraint = new ResourceConstraintElements());
	}
	
	public ParserRule getResourceConstraintRule() {
		return getResourceConstraintAccess().getRule();
	}

	//RequiredHardwareResourceInstanceConstraint returns cs::RequiredHardwareResourceInstanceConstraintCS:
	//	"requiredHardwareResourceInstance" name=ID? "{" "descriptors" tupleDescriptors+=ComponentResourceTupleDescriptor (","
	//	tupleDescriptors+=ComponentResourceTupleDescriptor)* ";" "ocl" expression=Model ";" "}";
	public RequiredHardwareResourceInstanceConstraintElements getRequiredHardwareResourceInstanceConstraintAccess() {
		return (pRequiredHardwareResourceInstanceConstraint != null) ? pRequiredHardwareResourceInstanceConstraint : (pRequiredHardwareResourceInstanceConstraint = new RequiredHardwareResourceInstanceConstraintElements());
	}
	
	public ParserRule getRequiredHardwareResourceInstanceConstraintRule() {
		return getRequiredHardwareResourceInstanceConstraintAccess().getRule();
	}

	//enum LocationConstraintType returns cs::LocationConstraintTypes:
	//	SAME_LOCATION="sameLocation" | DIFFERENT_LOCATION="differentLocation";
	public LocationConstraintTypeElements getLocationConstraintTypeAccess() {
		return (unknownRuleLocationConstraintType != null) ? unknownRuleLocationConstraintType : (unknownRuleLocationConstraintType = new LocationConstraintTypeElements());
	}
	
	public EnumRule getLocationConstraintTypeRule() {
		return getLocationConstraintTypeAccess().getRule();
	}

	//LocationTupleDescriptor returns cs::LocationTupleDescriptorCS:
	//	"(" instance=ID "," secondInstance=ID ")";
	public LocationTupleDescriptorElements getLocationTupleDescriptorAccess() {
		return (pLocationTupleDescriptor != null) ? pLocationTupleDescriptor : (pLocationTupleDescriptor = new LocationTupleDescriptorElements());
	}
	
	public ParserRule getLocationTupleDescriptorRule() {
		return getLocationTupleDescriptorAccess().getRule();
	}

	//ValueTupleDescriptor returns cs::ValueTupleDescriptorCS:
	//	value=ID;
	public ValueTupleDescriptorElements getValueTupleDescriptorAccess() {
		return (pValueTupleDescriptor != null) ? pValueTupleDescriptor : (pValueTupleDescriptor = new ValueTupleDescriptorElements());
	}
	
	public ParserRule getValueTupleDescriptorRule() {
		return getValueTupleDescriptorAccess().getRule();
	}

	//ComponentResourceTupleDescriptor returns cs::ComponentResourceTupleDescriptorCS:
	//	"(" instance=ID "," hwresinstance=ID ")";
	public ComponentResourceTupleDescriptorElements getComponentResourceTupleDescriptorAccess() {
		return (pComponentResourceTupleDescriptor != null) ? pComponentResourceTupleDescriptor : (pComponentResourceTupleDescriptor = new ComponentResourceTupleDescriptorElements());
	}
	
	public ParserRule getComponentResourceTupleDescriptorRule() {
		return getComponentResourceTupleDescriptorAccess().getRule();
	}

	//MeasureFunction returns cs::MeasureFunctionCS:
	//	"measure" services+=[cs::ServiceCS] ("+" services+=[cs::ServiceCS])* ";";
	public MeasureFunctionElements getMeasureFunctionAccess() {
		return (pMeasureFunction != null) ? pMeasureFunction : (pMeasureFunction = new MeasureFunctionElements());
	}
	
	public ParserRule getMeasureFunctionRule() {
		return getMeasureFunctionAccess().getRule();
	}

	////generate essentialOCLCST "http://www.eclipse.org/ocl/3.0.0/EssentialOCLCST"
	//Model returns ContextCS:
	//	ownedExpression=ExpCS;
	public EssentialOCLGrammarAccess.ModelElements getModelAccess() {
		return gaEssentialOCL.getModelAccess();
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//terminal fragment ESCAPED_CHARACTER:
	//	"\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\");
	public TerminalRule getESCAPED_CHARACTERRule() {
		return gaEssentialOCL.getESCAPED_CHARACTERRule();
	} 

	//terminal fragment LETTER_CHARACTER:
	//	"a".."z" | "A".."Z" | "_";
	public TerminalRule getLETTER_CHARACTERRule() {
		return gaEssentialOCL.getLETTER_CHARACTERRule();
	} 

	//terminal DOUBLE_QUOTED_STRING:
	//	"\"" (ESCAPED_CHARACTER | !("\\" | "\""))* "\"";
	public TerminalRule getDOUBLE_QUOTED_STRINGRule() {
		return gaEssentialOCL.getDOUBLE_QUOTED_STRINGRule();
	} 

	//terminal SINGLE_QUOTED_STRING:
	//	"\'" (ESCAPED_CHARACTER | !("\\" | "\'"))* "\'";
	public TerminalRule getSINGLE_QUOTED_STRINGRule() {
		return gaEssentialOCL.getSINGLE_QUOTED_STRINGRule();
	} 

	//terminal ML_SINGLE_QUOTED_STRING:
	//	"/\'"->"\'/";
	public TerminalRule getML_SINGLE_QUOTED_STRINGRule() {
		return gaEssentialOCL.getML_SINGLE_QUOTED_STRINGRule();
	} 

	//terminal SIMPLE_ID:
	//	LETTER_CHARACTER (LETTER_CHARACTER | "0".."9")*;
	public TerminalRule getSIMPLE_IDRule() {
		return gaEssentialOCL.getSIMPLE_IDRule();
	} 

	//terminal ESCAPED_ID:
	//	"_" SINGLE_QUOTED_STRING;
	public TerminalRule getESCAPED_IDRule() {
		return gaEssentialOCL.getESCAPED_IDRule();
	} 

	//ID:
	//	SIMPLE_ID | ESCAPED_ID;
	public EssentialOCLGrammarAccess.IDElements getIDAccess() {
		return gaEssentialOCL.getIDAccess();
	}
	
	public ParserRule getIDRule() {
		return getIDAccess().getRule();
	}

	//// String to allow diverse re-use
	//// multiple leading zeroes occur as floating point fractional part
	//terminal INT:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaEssentialOCL.getINTRule();
	} 

	//LOWER returns ecore::EInt:
	//	INT;
	public EssentialOCLGrammarAccess.LOWERElements getLOWERAccess() {
		return gaEssentialOCL.getLOWERAccess();
	}
	
	public ParserRule getLOWERRule() {
		return getLOWERAccess().getRule();
	}

	//UPPER returns ecore::EInt:
	//	INT | "*";
	public EssentialOCLGrammarAccess.UPPERElements getUPPERAccess() {
		return gaEssentialOCL.getUPPERAccess();
	}
	
	public ParserRule getUPPERRule() {
		return getUPPERAccess().getRule();
	}

	//// Not terminal to allow parser backtracking to sort out "5..7"
	//// EssentialOCLTokenSource pieces this together ('.' INT)? (('e' | 'E') ('+' | '-')? INT)?;
	//NUMBER_LITERAL returns BigNumber:
	//	INT;
	public EssentialOCLGrammarAccess.NUMBER_LITERALElements getNUMBER_LITERALAccess() {
		return gaEssentialOCL.getNUMBER_LITERALAccess();
	}
	
	public ParserRule getNUMBER_LITERALRule() {
		return getNUMBER_LITERALAccess().getRule();
	}

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaEssentialOCL.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"--" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaEssentialOCL.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaEssentialOCL.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaEssentialOCL.getANY_OTHERRule();
	} 

	//URI:
	//	SINGLE_QUOTED_STRING;
	public EssentialOCLGrammarAccess.URIElements getURIAccess() {
		return gaEssentialOCL.getURIAccess();
	}
	
	public ParserRule getURIRule() {
		return getURIAccess().getRule();
	}

	//EssentialOCLReservedKeyword:
	//	"and" | "else" | "endif" | "if" | "implies" | "in" | "let" | "not" | "or" | "then" | "xor";
	public EssentialOCLGrammarAccess.EssentialOCLReservedKeywordElements getEssentialOCLReservedKeywordAccess() {
		return gaEssentialOCL.getEssentialOCLReservedKeywordAccess();
	}
	
	public ParserRule getEssentialOCLReservedKeywordRule() {
		return getEssentialOCLReservedKeywordAccess().getRule();
	}

	//EssentialOCLUnaryOperatorCS returns UnaryOperatorCS:
	//	name=("-" | "not");
	public EssentialOCLGrammarAccess.EssentialOCLUnaryOperatorCSElements getEssentialOCLUnaryOperatorCSAccess() {
		return gaEssentialOCL.getEssentialOCLUnaryOperatorCSAccess();
	}
	
	public ParserRule getEssentialOCLUnaryOperatorCSRule() {
		return getEssentialOCLUnaryOperatorCSAccess().getRule();
	}

	//EssentialOCLInfixOperatorCS returns BinaryOperatorCS:
	//	name=("*" | "/" | "+" | "-" | ">" | "<" | ">=" | "<=" | "=" | "<>" | "and" | "or" | "xor" | "implies");
	public EssentialOCLGrammarAccess.EssentialOCLInfixOperatorCSElements getEssentialOCLInfixOperatorCSAccess() {
		return gaEssentialOCL.getEssentialOCLInfixOperatorCSAccess();
	}
	
	public ParserRule getEssentialOCLInfixOperatorCSRule() {
		return getEssentialOCLInfixOperatorCSAccess().getRule();
	}

	//EssentialOCLNavigationOperatorCS returns NavigationOperatorCS:
	//	name=("." | "->");
	public EssentialOCLGrammarAccess.EssentialOCLNavigationOperatorCSElements getEssentialOCLNavigationOperatorCSAccess() {
		return gaEssentialOCL.getEssentialOCLNavigationOperatorCSAccess();
	}
	
	public ParserRule getEssentialOCLNavigationOperatorCSRule() {
		return getEssentialOCLNavigationOperatorCSAccess().getRule();
	}

	//Identifier:
	//	ID;
	public EssentialOCLGrammarAccess.IdentifierElements getIdentifierAccess() {
		return gaEssentialOCL.getIdentifierAccess();
	}
	
	public ParserRule getIdentifierRule() {
		return getIdentifierAccess().getRule();
	}

	//StringLiteral:
	//	SINGLE_QUOTED_STRING;
	public EssentialOCLGrammarAccess.StringLiteralElements getStringLiteralAccess() {
		return gaEssentialOCL.getStringLiteralAccess();
	}
	
	public ParserRule getStringLiteralRule() {
		return getStringLiteralAccess().getRule();
	}

	//BinaryOperatorCS:
	//	InfixOperatorCS | NavigationOperatorCS;
	public EssentialOCLGrammarAccess.BinaryOperatorCSElements getBinaryOperatorCSAccess() {
		return gaEssentialOCL.getBinaryOperatorCSAccess();
	}
	
	public ParserRule getBinaryOperatorCSRule() {
		return getBinaryOperatorCSAccess().getRule();
	}

	//// Intended to be overrideable
	//InfixOperatorCS returns BinaryOperatorCS:
	//	EssentialOCLInfixOperatorCS;
	public EssentialOCLGrammarAccess.InfixOperatorCSElements getInfixOperatorCSAccess() {
		return gaEssentialOCL.getInfixOperatorCSAccess();
	}
	
	public ParserRule getInfixOperatorCSRule() {
		return getInfixOperatorCSAccess().getRule();
	}

	//// Intended to be overrideable
	//NavigationOperatorCS:
	//	EssentialOCLNavigationOperatorCS;
	public EssentialOCLGrammarAccess.NavigationOperatorCSElements getNavigationOperatorCSAccess() {
		return gaEssentialOCL.getNavigationOperatorCSAccess();
	}
	
	public ParserRule getNavigationOperatorCSRule() {
		return getNavigationOperatorCSAccess().getRule();
	}

	//// Intended to be overrideable
	//UnaryOperatorCS:
	//	EssentialOCLUnaryOperatorCS;
	public EssentialOCLGrammarAccess.UnaryOperatorCSElements getUnaryOperatorCSAccess() {
		return gaEssentialOCL.getUnaryOperatorCSAccess();
	}
	
	public ParserRule getUnaryOperatorCSRule() {
		return getUnaryOperatorCSAccess().getRule();
	}

	////---------------------------------------------------------------------
	////  Names
	////---------------------------------------------------------------------
	//EssentialOCLUnrestrictedName returns ecore::EString:
	//	Identifier;
	public EssentialOCLGrammarAccess.EssentialOCLUnrestrictedNameElements getEssentialOCLUnrestrictedNameAccess() {
		return gaEssentialOCL.getEssentialOCLUnrestrictedNameAccess();
	}
	
	public ParserRule getEssentialOCLUnrestrictedNameRule() {
		return getEssentialOCLUnrestrictedNameAccess().getRule();
	}

	//// Intended to be overridden
	//UnrestrictedName returns ecore::EString:
	//	EssentialOCLUnrestrictedName;
	public EssentialOCLGrammarAccess.UnrestrictedNameElements getUnrestrictedNameAccess() {
		return gaEssentialOCL.getUnrestrictedNameAccess();
	}
	
	public ParserRule getUnrestrictedNameRule() {
		return getUnrestrictedNameAccess().getRule();
	}

	//EssentialOCLUnreservedName returns ecore::EString:
	//	UnrestrictedName | CollectionTypeIdentifier | PrimitiveTypeIdentifier | "Tuple";
	public EssentialOCLGrammarAccess.EssentialOCLUnreservedNameElements getEssentialOCLUnreservedNameAccess() {
		return gaEssentialOCL.getEssentialOCLUnreservedNameAccess();
	}
	
	public ParserRule getEssentialOCLUnreservedNameRule() {
		return getEssentialOCLUnreservedNameAccess().getRule();
	}

	//// Intended to be overridden
	//UnreservedName returns ecore::EString:
	//	EssentialOCLUnreservedName;
	public EssentialOCLGrammarAccess.UnreservedNameElements getUnreservedNameAccess() {
		return gaEssentialOCL.getUnreservedNameAccess();
	}
	
	public ParserRule getUnreservedNameRule() {
		return getUnreservedNameAccess().getRule();
	}

	//PathNameCS returns base::PathNameCS:
	//	path+=FirstPathElementCS ("::" path+=NextPathElementCS)*;
	public EssentialOCLGrammarAccess.PathNameCSElements getPathNameCSAccess() {
		return gaEssentialOCL.getPathNameCSAccess();
	}
	
	public ParserRule getPathNameCSRule() {
		return getPathNameCSAccess().getRule();
	}

	//FirstPathElementCS returns base::PathElementCS:
	//	element=[pivot::NamedElement|UnrestrictedName];
	public EssentialOCLGrammarAccess.FirstPathElementCSElements getFirstPathElementCSAccess() {
		return gaEssentialOCL.getFirstPathElementCSAccess();
	}
	
	public ParserRule getFirstPathElementCSRule() {
		return getFirstPathElementCSAccess().getRule();
	}

	//NextPathElementCS returns base::PathElementCS:
	//	element=[pivot::NamedElement|UnreservedName];
	public EssentialOCLGrammarAccess.NextPathElementCSElements getNextPathElementCSAccess() {
		return gaEssentialOCL.getNextPathElementCSAccess();
	}
	
	public ParserRule getNextPathElementCSRule() {
		return getNextPathElementCSAccess().getRule();
	}

	//URIPathNameCS returns base::PathNameCS:
	//	path+=URIFirstPathElementCS ("::" path+=NextPathElementCS)*;
	public EssentialOCLGrammarAccess.URIPathNameCSElements getURIPathNameCSAccess() {
		return gaEssentialOCL.getURIPathNameCSAccess();
	}
	
	public ParserRule getURIPathNameCSRule() {
		return getURIPathNameCSAccess().getRule();
	}

	//URIFirstPathElementCS returns base::PathElementCS:
	//	element=[pivot::NamedElement|UnrestrictedName] | {base::PathElementWithURICS} element=[pivot::Namespace|URI];
	public EssentialOCLGrammarAccess.URIFirstPathElementCSElements getURIFirstPathElementCSAccess() {
		return gaEssentialOCL.getURIFirstPathElementCSAccess();
	}
	
	public ParserRule getURIFirstPathElementCSRule() {
		return getURIFirstPathElementCSAccess().getRule();
	}

	////---------------------------------------------------------------------
	////  Types
	////---------------------------------------------------------------------
	//PrimitiveTypeIdentifier:
	//	"Boolean" | "Integer" | "Real" | "String" | "UnlimitedNatural" | "OclAny" | "OclInvalid" | "OclVoid";
	public EssentialOCLGrammarAccess.PrimitiveTypeIdentifierElements getPrimitiveTypeIdentifierAccess() {
		return gaEssentialOCL.getPrimitiveTypeIdentifierAccess();
	}
	
	public ParserRule getPrimitiveTypeIdentifierRule() {
		return getPrimitiveTypeIdentifierAccess().getRule();
	}

	//PrimitiveTypeCS returns base::PrimitiveTypeRefCS:
	//	name=PrimitiveTypeIdentifier;
	public EssentialOCLGrammarAccess.PrimitiveTypeCSElements getPrimitiveTypeCSAccess() {
		return gaEssentialOCL.getPrimitiveTypeCSAccess();
	}
	
	public ParserRule getPrimitiveTypeCSRule() {
		return getPrimitiveTypeCSAccess().getRule();
	}

	//CollectionTypeIdentifier returns ecore::EString:
	//	"Set" | "Bag" | "Sequence" | "Collection" | "OrderedSet";
	public EssentialOCLGrammarAccess.CollectionTypeIdentifierElements getCollectionTypeIdentifierAccess() {
		return gaEssentialOCL.getCollectionTypeIdentifierAccess();
	}
	
	public ParserRule getCollectionTypeIdentifierRule() {
		return getCollectionTypeIdentifierAccess().getRule();
	}

	//CollectionTypeCS:
	//	name=CollectionTypeIdentifier ("(" ownedType=TypeExpCS ")")?;
	public EssentialOCLGrammarAccess.CollectionTypeCSElements getCollectionTypeCSAccess() {
		return gaEssentialOCL.getCollectionTypeCSAccess();
	}
	
	public ParserRule getCollectionTypeCSRule() {
		return getCollectionTypeCSAccess().getRule();
	}

	//MultiplicityBoundsCS returns base::MultiplicityBoundsCS:
	//	lowerBound=LOWER (".." upperBound=UPPER)?;
	public EssentialOCLGrammarAccess.MultiplicityBoundsCSElements getMultiplicityBoundsCSAccess() {
		return gaEssentialOCL.getMultiplicityBoundsCSAccess();
	}
	
	public ParserRule getMultiplicityBoundsCSRule() {
		return getMultiplicityBoundsCSAccess().getRule();
	}

	//MultiplicityCS returns base::MultiplicityCS:
	//	"[" (MultiplicityBoundsCS | MultiplicityStringCS) "]";
	public EssentialOCLGrammarAccess.MultiplicityCSElements getMultiplicityCSAccess() {
		return gaEssentialOCL.getMultiplicityCSAccess();
	}
	
	public ParserRule getMultiplicityCSRule() {
		return getMultiplicityCSAccess().getRule();
	}

	//MultiplicityStringCS returns base::MultiplicityStringCS:
	//	stringBounds=("*" | "+" | "?");
	public EssentialOCLGrammarAccess.MultiplicityStringCSElements getMultiplicityStringCSAccess() {
		return gaEssentialOCL.getMultiplicityStringCSAccess();
	}
	
	public ParserRule getMultiplicityStringCSRule() {
		return getMultiplicityStringCSAccess().getRule();
	}

	//TupleTypeCS returns base::TupleTypeCS:
	//	name="Tuple" ("(" (ownedParts+=TuplePartCS ("," ownedParts+=TuplePartCS)*)? ")")?;
	public EssentialOCLGrammarAccess.TupleTypeCSElements getTupleTypeCSAccess() {
		return gaEssentialOCL.getTupleTypeCSAccess();
	}
	
	public ParserRule getTupleTypeCSRule() {
		return getTupleTypeCSAccess().getRule();
	}

	//TuplePartCS returns base::TuplePartCS:
	//	name=UnrestrictedName ":" ownedType=TypeExpCS;
	public EssentialOCLGrammarAccess.TuplePartCSElements getTuplePartCSAccess() {
		return gaEssentialOCL.getTuplePartCSAccess();
	}
	
	public ParserRule getTuplePartCSRule() {
		return getTuplePartCSAccess().getRule();
	}

	////---------------------------------------------------------------------
	////  Literals
	////---------------------------------------------------------------------
	//CollectionLiteralExpCS:
	//	ownedType=CollectionTypeCS "{" (ownedParts+=CollectionLiteralPartCS ("," ownedParts+=CollectionLiteralPartCS)*)? "}";
	public EssentialOCLGrammarAccess.CollectionLiteralExpCSElements getCollectionLiteralExpCSAccess() {
		return gaEssentialOCL.getCollectionLiteralExpCSAccess();
	}
	
	public ParserRule getCollectionLiteralExpCSRule() {
		return getCollectionLiteralExpCSAccess().getRule();
	}

	//CollectionLiteralPartCS:
	//	expressionCS=ExpCS (".." lastExpressionCS=ExpCS)?;
	public EssentialOCLGrammarAccess.CollectionLiteralPartCSElements getCollectionLiteralPartCSAccess() {
		return gaEssentialOCL.getCollectionLiteralPartCSAccess();
	}
	
	public ParserRule getCollectionLiteralPartCSRule() {
		return getCollectionLiteralPartCSAccess().getRule();
	}

	//ConstructorPartCS:
	//	property=[pivot::Property|UnrestrictedName] "=" initExpression=ExpCS;
	public EssentialOCLGrammarAccess.ConstructorPartCSElements getConstructorPartCSAccess() {
		return gaEssentialOCL.getConstructorPartCSAccess();
	}
	
	public ParserRule getConstructorPartCSRule() {
		return getConstructorPartCSAccess().getRule();
	}

	//PrimitiveLiteralExpCS:
	//	NumberLiteralExpCS | StringLiteralExpCS | BooleanLiteralExpCS | UnlimitedNaturalLiteralExpCS | InvalidLiteralExpCS |
	//	NullLiteralExpCS;
	public EssentialOCLGrammarAccess.PrimitiveLiteralExpCSElements getPrimitiveLiteralExpCSAccess() {
		return gaEssentialOCL.getPrimitiveLiteralExpCSAccess();
	}
	
	public ParserRule getPrimitiveLiteralExpCSRule() {
		return getPrimitiveLiteralExpCSAccess().getRule();
	}

	//TupleLiteralExpCS:
	//	"Tuple" "{" ownedParts+=TupleLiteralPartCS ("," ownedParts+=TupleLiteralPartCS)* "}";
	public EssentialOCLGrammarAccess.TupleLiteralExpCSElements getTupleLiteralExpCSAccess() {
		return gaEssentialOCL.getTupleLiteralExpCSAccess();
	}
	
	public ParserRule getTupleLiteralExpCSRule() {
		return getTupleLiteralExpCSAccess().getRule();
	}

	//TupleLiteralPartCS:
	//	name=UnrestrictedName (":" ownedType=TypeExpCS)? "=" initExpression=ExpCS;
	public EssentialOCLGrammarAccess.TupleLiteralPartCSElements getTupleLiteralPartCSAccess() {
		return gaEssentialOCL.getTupleLiteralPartCSAccess();
	}
	
	public ParserRule getTupleLiteralPartCSRule() {
		return getTupleLiteralPartCSAccess().getRule();
	}

	//NumberLiteralExpCS:
	//	name=NUMBER_LITERAL;
	public EssentialOCLGrammarAccess.NumberLiteralExpCSElements getNumberLiteralExpCSAccess() {
		return gaEssentialOCL.getNumberLiteralExpCSAccess();
	}
	
	public ParserRule getNumberLiteralExpCSRule() {
		return getNumberLiteralExpCSAccess().getRule();
	}

	//StringLiteralExpCS:
	//	name+=StringLiteral+;
	public EssentialOCLGrammarAccess.StringLiteralExpCSElements getStringLiteralExpCSAccess() {
		return gaEssentialOCL.getStringLiteralExpCSAccess();
	}
	
	public ParserRule getStringLiteralExpCSRule() {
		return getStringLiteralExpCSAccess().getRule();
	}

	//BooleanLiteralExpCS:
	//	name="true" | name="false";
	public EssentialOCLGrammarAccess.BooleanLiteralExpCSElements getBooleanLiteralExpCSAccess() {
		return gaEssentialOCL.getBooleanLiteralExpCSAccess();
	}
	
	public ParserRule getBooleanLiteralExpCSRule() {
		return getBooleanLiteralExpCSAccess().getRule();
	}

	//UnlimitedNaturalLiteralExpCS:
	//	{UnlimitedNaturalLiteralExpCS} "*";
	public EssentialOCLGrammarAccess.UnlimitedNaturalLiteralExpCSElements getUnlimitedNaturalLiteralExpCSAccess() {
		return gaEssentialOCL.getUnlimitedNaturalLiteralExpCSAccess();
	}
	
	public ParserRule getUnlimitedNaturalLiteralExpCSRule() {
		return getUnlimitedNaturalLiteralExpCSAccess().getRule();
	}

	//InvalidLiteralExpCS:
	//	{InvalidLiteralExpCS} "invalid";
	public EssentialOCLGrammarAccess.InvalidLiteralExpCSElements getInvalidLiteralExpCSAccess() {
		return gaEssentialOCL.getInvalidLiteralExpCSAccess();
	}
	
	public ParserRule getInvalidLiteralExpCSRule() {
		return getInvalidLiteralExpCSAccess().getRule();
	}

	//NullLiteralExpCS:
	//	{NullLiteralExpCS} "null";
	public EssentialOCLGrammarAccess.NullLiteralExpCSElements getNullLiteralExpCSAccess() {
		return gaEssentialOCL.getNullLiteralExpCSAccess();
	}
	
	public ParserRule getNullLiteralExpCSRule() {
		return getNullLiteralExpCSAccess().getRule();
	}

	//TypeLiteralCS returns base::TypedRefCS:
	//	PrimitiveTypeCS | CollectionTypeCS | TupleTypeCS;
	public EssentialOCLGrammarAccess.TypeLiteralCSElements getTypeLiteralCSAccess() {
		return gaEssentialOCL.getTypeLiteralCSAccess();
	}
	
	public ParserRule getTypeLiteralCSRule() {
		return getTypeLiteralCSAccess().getRule();
	}

	//TypeLiteralWithMultiplicityCS returns base::TypedRefCS:
	//	TypeLiteralCS multiplicity=MultiplicityCS?;
	public EssentialOCLGrammarAccess.TypeLiteralWithMultiplicityCSElements getTypeLiteralWithMultiplicityCSAccess() {
		return gaEssentialOCL.getTypeLiteralWithMultiplicityCSAccess();
	}
	
	public ParserRule getTypeLiteralWithMultiplicityCSRule() {
		return getTypeLiteralWithMultiplicityCSAccess().getRule();
	}

	//TypeLiteralExpCS:
	//	ownedType=TypeLiteralWithMultiplicityCS;
	public EssentialOCLGrammarAccess.TypeLiteralExpCSElements getTypeLiteralExpCSAccess() {
		return gaEssentialOCL.getTypeLiteralExpCSAccess();
	}
	
	public ParserRule getTypeLiteralExpCSRule() {
		return getTypeLiteralExpCSAccess().getRule();
	}

	//TypeNameExpCS:
	//	pathName=PathNameCS;
	public EssentialOCLGrammarAccess.TypeNameExpCSElements getTypeNameExpCSAccess() {
		return gaEssentialOCL.getTypeNameExpCSAccess();
	}
	
	public ParserRule getTypeNameExpCSRule() {
		return getTypeNameExpCSAccess().getRule();
	}

	//TypeExpCS returns base::TypedRefCS:
	//	(TypeNameExpCS | TypeLiteralCS) multiplicity=MultiplicityCS?;
	public EssentialOCLGrammarAccess.TypeExpCSElements getTypeExpCSAccess() {
		return gaEssentialOCL.getTypeExpCSAccess();
	}
	
	public ParserRule getTypeExpCSRule() {
		return getTypeExpCSAccess().getRule();
	}

	////---------------------------------------------------------------------
	////  Expressions
	////---------------------------------------------------------------------
	//// An ExpCS permits a LetExpCS only in the final term to ensure
	////  that let is right associative, whereas infix operators are left associative.
	////   a = 64 / 16 / let b : Integer in 8 / let c : Integer in 4 
	//// is
	////   a = (64 / 16) / (let b : Integer in 8 / (let c : Integer in 4 ))
	//ExpCS:
	//	PrefixedExpCS ({InfixExpCS.ownedExpression+=current} ownedOperator+=BinaryOperatorCS (ownedExpression+=PrefixedExpCS
	//	(ownedOperator+=BinaryOperatorCS ownedExpression+=PrefixedExpCS)* (ownedOperator+=BinaryOperatorCS
	//	ownedExpression+=LetExpCS)? | ownedExpression+=LetExpCS))? | {PrefixExpCS} ownedOperator+=UnaryOperatorCS+
	//	ownedExpression=LetExpCS | LetExpCS;
	public EssentialOCLGrammarAccess.ExpCSElements getExpCSAccess() {
		return gaEssentialOCL.getExpCSAccess();
	}
	
	public ParserRule getExpCSRule() {
		return getExpCSAccess().getRule();
	}

	//PrefixedExpCS returns ExpCS:
	//	{PrefixExpCS} ownedOperator+=UnaryOperatorCS+ ownedExpression=PrimaryExpCS | PrimaryExpCS;
	public EssentialOCLGrammarAccess.PrefixedExpCSElements getPrefixedExpCSAccess() {
		return gaEssentialOCL.getPrefixedExpCSAccess();
	}
	
	public ParserRule getPrefixedExpCSRule() {
		return getPrefixedExpCSAccess().getRule();
	}

	//PrimaryExpCS returns ExpCS:
	//	NestedExpCS | IfExpCS | SelfExpCS | PrimitiveLiteralExpCS | TupleLiteralExpCS | CollectionLiteralExpCS |
	//	TypeLiteralExpCS | {NameExpCS} pathName=PathNameCS ({IndexExpCS.nameExp=current} "[" firstIndexes+=ExpCS (","
	//	firstIndexes+=ExpCS)* "]" ("[" secondIndexes+=ExpCS ("," secondIndexes+=ExpCS)* "]")? (atPre?="@" "pre")? |
	//	{ConstructorExpCS.nameExp=current} "{" ((ownedParts+=ConstructorPartCS ("," ownedParts+=ConstructorPartCS)*)? |
	//	value=StringLiteral) "}" | (atPre?="@" "pre")? ({InvocationExpCS.nameExp=current} "(" (argument+=NavigatingArgCS
	//	argument+=NavigatingCommaArgCS* (argument+=NavigatingSemiArgCS argument+=NavigatingCommaArgCS*)?
	//	(argument+=NavigatingBarArgCS argument+=NavigatingCommaArgCS*)?)? ")")?);
	public EssentialOCLGrammarAccess.PrimaryExpCSElements getPrimaryExpCSAccess() {
		return gaEssentialOCL.getPrimaryExpCSAccess();
	}
	
	public ParserRule getPrimaryExpCSRule() {
		return getPrimaryExpCSAccess().getRule();
	}

	//// Type-less init is an illegal infix expression
	//NavigatingArgCS:
	//	name=NavigatingArgExpCS (":" ownedType=TypeExpCS ("=" init=ExpCS)?)?;
	public EssentialOCLGrammarAccess.NavigatingArgCSElements getNavigatingArgCSAccess() {
		return gaEssentialOCL.getNavigatingArgCSAccess();
	}
	
	public ParserRule getNavigatingArgCSRule() {
		return getNavigatingArgCSAccess().getRule();
	}

	//// Type-less init is an illegal infix expression
	//NavigatingBarArgCS returns NavigatingArgCS:
	//	prefix="|" name=NavigatingArgExpCS (":" ownedType=TypeExpCS ("=" init=ExpCS)?)?;
	public EssentialOCLGrammarAccess.NavigatingBarArgCSElements getNavigatingBarArgCSAccess() {
		return gaEssentialOCL.getNavigatingBarArgCSAccess();
	}
	
	public ParserRule getNavigatingBarArgCSRule() {
		return getNavigatingBarArgCSAccess().getRule();
	}

	//// Type-less init is an illegal infix expression
	//NavigatingCommaArgCS returns NavigatingArgCS:
	//	prefix="," name=NavigatingArgExpCS (":" ownedType=TypeExpCS ("=" init=ExpCS)?)?;
	public EssentialOCLGrammarAccess.NavigatingCommaArgCSElements getNavigatingCommaArgCSAccess() {
		return gaEssentialOCL.getNavigatingCommaArgCSAccess();
	}
	
	public ParserRule getNavigatingCommaArgCSRule() {
		return getNavigatingCommaArgCSAccess().getRule();
	}

	//// Type-less init is an illegal infix expression
	//NavigatingSemiArgCS returns NavigatingArgCS:
	//	prefix=";" name=NavigatingArgExpCS (":" ownedType=TypeExpCS ("=" init=ExpCS)?)?;
	public EssentialOCLGrammarAccess.NavigatingSemiArgCSElements getNavigatingSemiArgCSAccess() {
		return gaEssentialOCL.getNavigatingSemiArgCSAccess();
	}
	
	public ParserRule getNavigatingSemiArgCSRule() {
		return getNavigatingSemiArgCSAccess().getRule();
	}

	//// Intended to be overridden
	////	'?'	-- defined by Complete OCL
	//NavigatingArgExpCS returns ExpCS:
	//	ExpCS;
	public EssentialOCLGrammarAccess.NavigatingArgExpCSElements getNavigatingArgExpCSAccess() {
		return gaEssentialOCL.getNavigatingArgExpCSAccess();
	}
	
	public ParserRule getNavigatingArgExpCSRule() {
		return getNavigatingArgExpCSAccess().getRule();
	}

	//IfExpCS:
	//	"if" condition=ExpCS "then" thenExpression=ExpCS "else" elseExpression=ExpCS "endif";
	public EssentialOCLGrammarAccess.IfExpCSElements getIfExpCSAccess() {
		return gaEssentialOCL.getIfExpCSAccess();
	}
	
	public ParserRule getIfExpCSRule() {
		return getIfExpCSAccess().getRule();
	}

	//LetExpCS:
	//	"let" variable+=LetVariableCS ("," variable+=LetVariableCS)* "in" in=ExpCS;
	public EssentialOCLGrammarAccess.LetExpCSElements getLetExpCSAccess() {
		return gaEssentialOCL.getLetExpCSAccess();
	}
	
	public ParserRule getLetExpCSRule() {
		return getLetExpCSAccess().getRule();
	}

	//LetVariableCS:
	//	name=UnrestrictedName (":" ownedType=TypeExpCS)? "=" initExpression=ExpCS;
	public EssentialOCLGrammarAccess.LetVariableCSElements getLetVariableCSAccess() {
		return gaEssentialOCL.getLetVariableCSAccess();
	}
	
	public ParserRule getLetVariableCSRule() {
		return getLetVariableCSAccess().getRule();
	}

	//NestedExpCS:
	//	"(" source=ExpCS ")";
	public EssentialOCLGrammarAccess.NestedExpCSElements getNestedExpCSAccess() {
		return gaEssentialOCL.getNestedExpCSAccess();
	}
	
	public ParserRule getNestedExpCSRule() {
		return getNestedExpCSAccess().getRule();
	}

	//SelfExpCS:
	//	{SelfExpCS} "self";
	public EssentialOCLGrammarAccess.SelfExpCSElements getSelfExpCSAccess() {
		return gaEssentialOCL.getSelfExpCSAccess();
	}
	
	public ParserRule getSelfExpCSRule() {
		return getSelfExpCSAccess().getRule();
	}
}
