/**
 * generated by Xtext 2.11.0
 */
package de.fraunhofer.iem.ide;

import com.google.inject.Injector;
import de.fraunhofer.iem.ProjectPlanningStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ProjectPlanningIdeSetup extends ProjectPlanningStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from ProjectPlanningIdeModule to Module");
  }
}
