/**
 * generated by Xtext 2.11.0
 */
package de.fraunhofer.iem.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ProjectPlanningIdeModule /* implements AbstractProjectPlanningIdeModule  */{
}
