/*
 * generated by Xtext 2.10.0
 */
package de.fraunhofer.iem.ui.tests;

import com.google.inject.Injector;
import de.fraunhofer.iem.projectPlanning.ui.internal.ProjectPlanningActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class ProjectPlanningUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ProjectPlanningActivator.getInstance().getInjector("de.fraunhofer.iem.ProjectPlanning");
	}

}
