/*
 * generated by Xtext
 */
package de.uni_paderborn.fujaba.muml.allocation.language.ui.contentassist

import de.uni_paderborn.fujaba.muml.allocation.language.ui.contentassist.AbstractAllocationSpecificationProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class AllocationSpecificationProposalProvider extends AbstractAllocationSpecificationProposalProvider {
}
