<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="config" nsURI="http://www.muml.org/eloquent/algorithm/ilp/neos/cplex/config/1.0.0"
    nsPrefix="config">
  <eClassifiers xsi:type="ecore:EClass" name="CPLEXConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CPLEXExportConfiguration">
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.muml.psm.allocation.algorithm.ilp.config/model/config.ecore#//ILPExportConfiguration">
      <eTypeArguments eClassifier="#//CPLEXConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
